[package]
name = "cedar"
version = "0.1.1"
authors = ["Tom Schroeder <j.tom.schroeder@gmail.com>"]
description = "Reactive, functional library for creating GUI applications"

documentation = "https://docs.rs/crate/cedar"
homepage = "https://github.com/jtomschroeder/cedar"
repository = "https://github.com/jtomschroeder/cedar"

readme = "README.md"
license = "MIT"
keywords = ["frp", "gui"]

[build-dependencies]
cc = "1.0"

[dependencies]
crossbeam = "0.3"

serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[dependencies.gtk]
version = "0.2.0"
features = ["v3_10"]
optional = true
