[package]
name = "cedar"
version = "0.1.1"
authors = ["Tom Schroeder <j.tom.schroeder@gmail.com>"]
description = "Reactive, functional library for creating GUI applications"

documentation = "https://docs.rs/crate/cedar"
homepage = "https://github.com/jtomschroeder/cedar"
repository = "https://github.com/jtomschroeder/cedar"

readme = "README.md"
license = "MIT"
keywords = ["frp", "gui"]

[dependencies]
crossbeam = "0.2.10"

serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

yoga = { path = "yoga" }
